version: "3"
services:
  ceph:
    image: ceph/daemon:v3.0.5-stable-3.0-luminous-centos-7
    environment:
      - CEPH_DEMO_UID=ceph-admin
      - CEPH_DEMO_ACCESS_KEY=accesskey
      - CEPH_DEMO_SECRET_KEY=secretkey
      - CEPH_DEMO_BUCKET=demobucket
      - RGW_NAME=localhost
      - RGW_CIVETWEB_PORT=8010
      - NETWORK_AUTO_DETECT=4
      - RESTAPI_LOG_LEVEL=debug
    ports:
      - 8010:8010
      - 5000:5000
    command: demo
    network_mode: host
  postgres-server:
    image: wbaa/airlock-dev-apache-ranger-postgres:0.0.13
  ranger-admin:
    network_mode: host
    image: wbaa/airlock-dev-apache-ranger:0.0.16
    stdin_open: true
    tty: true
    depends_on:
    - "postgres-server"
    - "ceph"
    ports:
    - "6080:6080"
  atlas:
    network_mode: host
    # image: wbaa/airlock-dev-apache-atlas:0.0.5
    build:
      context: .
    ports:
    - "21000:21000"
    expose:
    - "21000"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet
